name: Skill Documentation Issue
description: Report issues with skill documentation
title: "[Skill Docs]: "
labels: ["documentation", "skill-content"]
assignees:
  - secondsky
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a documentation issue!

        This template is for issues with skill documentation files (SKILL.md, README.md, references/, templates/).

  - type: checkboxes
    id: pre-submission
    attributes:
      label: Pre-submission Checklist
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: I have verified this is a documentation issue (not a code bug)
          required: true

  - type: input
    id: plugin-name
    attributes:
      label: Plugin/Skill Name
      description: Which skill's documentation has the issue?
      placeholder: "cloudflare-d1"
    validations:
      required: true

  - type: dropdown
    id: doc-type
    attributes:
      label: Documentation Type
      description: Which documentation file has the issue?
      options:
        - SKILL.md (main skill content)
        - README.md (public description)
        - references/ files (extended documentation)
        - templates/ (code examples)
        - plugin.json (metadata)
        - scripts/ (helper scripts)
        - Other (specify below)
    validations:
      required: true

  - type: input
    id: file-path
    attributes:
      label: File Path
      description: Specific file within the plugin directory
      placeholder: "plugins/cloudflare-d1/skills/cloudflare-d1/SKILL.md"
    validations:
      required: true

  - type: dropdown
    id: issue-type
    attributes:
      label: Issue Type
      description: What kind of documentation issue?
      options:
        - Incorrect/outdated information
        - Missing "When to Load References" section
        - Progressive disclosure issues (SKILL.md too long)
        - Missing keywords in metadata
        - Broken internal links
        - Code example doesn't work
        - Missing version information
        - Typo/grammar/formatting
        - Missing documentation
        - Unclear instructions
        - Other (describe below)
    validations:
      required: true

  - type: textarea
    id: current-doc
    attributes:
      label: Current Documentation
      description: Quote the problematic section (or describe what's missing)
      placeholder: |
        Current text:
        ```
        To set up D1, run: wrangler d1 create my-db
        ```

        OR

        Missing: The skill doesn't explain when to use batch vs individual operations.
      render: markdown
    validations:
      required: true

  - type: textarea
    id: suggested-improvement
    attributes:
      label: Suggested Improvement
      description: How should it be fixed?
      placeholder: |
        Should say:
        ```
        To set up D1, run: wrangler d1 create my-db --location [auto|weur|enam|apac]
        ```

        OR

        Add a new section:
        ## Batch vs Individual Operations
        - Use batch when: ...
        - Use individual when: ...
      render: markdown
    validations:
      required: true

  - type: textarea
    id: why-matters
    attributes:
      label: Why This Matters
      description: Impact on discoverability/usability
      placeholder: |
        This affects:
        - Skill discoverability (missing keywords)
        - User success rate (unclear instructions)
        - Token budget (missing progressive disclosure)
        - Standards compliance (wrong format)
    validations:
      required: true

  - type: textarea
    id: related-standards
    attributes:
      label: Related Standards
      description: Link to relevant checklists or standards
      placeholder: |
        - [ONE_PAGE_CHECKLIST.md Section 3](https://github.com/secondsky/claude-skills/blob/main/docs/getting-started/ONE_PAGE_CHECKLIST.md#section-3-documentation-quality)
        - [claude-code-skill-standards.md](https://github.com/secondsky/claude-skills/blob/main/docs/reference/claude-code-skill-standards.md)
      render: markdown

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      options:
        - label: I am willing to submit a PR to fix this
          required: false
        - label: I have verified the suggested improvement against skill standards
          required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Screenshots, links, or other relevant information
      placeholder: "Add any other context about the documentation issue here..."
