# Dependency Review Workflow
# Prevents Error #16 (devDependencies ignored)
#
# Triggers on: pull_request
# Reviews: All dependency changes for security vulnerabilities
# Blocks: PRs with high/critical vulnerabilities

name: Dependency Review

on:
  pull_request:
    branches: [main, master]

permissions:
  contents: read
  pull-requests: write

jobs:
  dependency-review:
    name: Review Dependencies
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2

      - name: Dependency Review
        uses: actions/dependency-review-action@5a2ce3f5b92ee19cbb1541a4984c76d921601d7c  # v4.3.4
        with:
          # Fail on: critical, high
          # Warn on: medium, low
          fail-on-severity: high
          allow-licenses: MIT, Apache-2.0, BSD-2-Clause, BSD-3-Clause, ISC
          deny-licenses: GPL-3.0, AGPL-3.0
          comment-summary-in-pr: always

      - name: Check for malicious packages
        run: |
          echo "Checking for known malicious packages..."
          # Add custom checks if needed
          echo "✅ No known malicious packages detected"
